version: 2
jobs:
  unit_test:
    docker:
      - image: golang:1.13.4
    steps:
      - checkout
      - run:
          name: Run unit tests
          command:
            sh bin/test

workflows:
  version: 2
  workflow:
    jobs:
    - unit_test
